### ISSUE TITLE
Documentation for Command Line Interface is out of date

### ISSUE THREAD

**Issue by dvcorreia** [ImagingDataCommons/dicomweb-client#103]
Documentation at  <https://dicomweb-client.readthedocs.io/en/latest/usage.html#command-line-interface-cli> seems to be out of date.

**Comment by CPBridge** [comment]
Oh no I see what's happened here. When I re-did the packaging metadata (#102) I accidentally changed the CLI script name from `dicomweb_client` to `dicomweb-client`. This was not an intentional change.

I suggest that since the new version with this issue has been released for < 24 hrs, the best way forward would be to change back to `dicomweb_client`, release a new version and try to pretend this never happened...

Sorry about the confusion

**Comment by CPBridge** [comment]
See #104

**Comment by CPBridge** [comment]
Resolved by #104 

I did also just fix the `--bearer-token` reference in the docs
