### ISSUE TITLE
retrieve and store instance, resulting in RGB always

### ISSUE THREAD

**Issue by jenny-hm-lee** [ImagingDataCommons/dicomweb-client#107]
Hello

I am using dicomweb-client and pydicom in my application. My application is roughly outline below.

1. use dicomweb client's retrieve_instances() to retrieve series from PACS, and return as pydicom dataset.  
2. change the study uid, series uid and instance uid of the pydicom dataset
3. store the modified pydicom dataset to PACs using dicomweb's client store_instance function().  I used the default transfer syntax.  

After storing the PACS, I notice the PhotometricInterpretation that was previously YBR_RCT is now RBG. How do I store the dicom to PACS keeping the original PhotometricInterpretation?

Thanks,
Jenny

**Comment by CPBridge** [comment]
@jenny-hm-lee I was thinking about this and I should probably be clearer. If you are requesting images using the default value for the `media_types` parameter of the `retrieve_instance` (i.e. not specifying the media type), then it will be requested in Implicit VR Little Endian, which will cause the server to decompress the pixel data which will result in a conversion of photometric interpretation also because YBR_RCT cannot be used with the Implicit VR Little Endian transfer syntax.

If you want the images to be retrieved as in JPEG2000, you can specify `media_types=(('application/dicom', '1.2.840.10008.1.2.4.90', )` in your call to `retrieve_instance`, `retrieve_series` or `retrieve_study`. But it's probably best to do this only if you know the data are originally stored as JPEG2000 (otherwise the server may need to re-encode/transcode it). Alternatively you could specify `media_types=(('application/dicom', '*'), )`, which requests any available transfer syntax, to which the PACS will *usually* respond with the transfer syntax in which the data is actually stored. But it's up to the PACS how to handle this situation so some may behave differently.

**Comment by jenny-hm-lee** [comment]
Sorry for late response.
Thanks very much, @CPBridge and @pieper 

In `retrieve_series`, I didn't specify `media_type` and `transfer_syntax`, because I was learning and just following the example in the website.   Since then, thank your comment,  I specify `media_types=(('application/dicom', '*'), )`, and now the retrieved dicom remains as YBR_RCT.

Thanks.
